# Generated by Django 5.0.1 on 2024-04-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(default='No summary provided'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
