# Generated by Django 5.0.1 on 2024-05-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ocr_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
